nycmeshnet/nycmesh-dns

mesh.zone
A novel method for delivering deep fried tori.
=> Add donuts.mesh

mesh.zone
=> netbox in A

mesh.zone
This updates the IP address for petra to better match existing usage and allocation.
=> Swap petra & crichton; add petra ipmi

mesh.zone
Tried to copy the existing structure for NS records, but please check this carefully and let me know if it needs changes
=> Add an andrew.mesh NS under Andrew's VPN node

mesh.zone
Temporary home of the status page
=> Add cursed status page

mesh.zone
Updates DNS record to point at digitalocean droplet instead of Andy's personal AWS machine
=> Update status page DNS

mesh.zone
Add entry for a box we're hosting services out of
=> Add meshsvc

mesh.zone
Creates an A record and a wildcard CNAME for the new Public IP at the Grand Street Box
=> Add grandsvc

mesh.zone
Add record for production meshdb
=> Mesh DB Prod

mesh.zone
=> Eliminate tv, add uptime kuma

mesh.zone
Add cname for dev env of https://github.com/nycmeshnet/wiki-infra
=> Add devwiki

mesh.zone
Add temporary CNAME wiki2 for testing prod wiki migration
=> Add wiki2 cname

mesh.zone
=> Add los CNAMEs

mesh.zone
Hopefully the last pair of services for a while
=> Add los-backend CNAMEs

mesh.zone
It's usually only up when theres sunlight
=> Add solar.mesh

mesh.zone
I'm hoping to take care of dev in a way that will make someone very happy.
=> Add pgadmin subdomain for meshdb prod

sld/records.nycmesh.net.tf
Fix the host of some of the new subdomains.
=> Fix host of devdb subdomains

mesh.zone, sld/records.nycmesh.net.tf
`gsg-displays.mesh.nycmesh.net` -> `gsg-displays.nycmesh.net`
=> Move gsg-displays to sld

mesh.zone
Adds
- Jon (hi jon)
- nycmesh-10-r630-01
- nycmesh-713-r630-01-mgmt
- nycmesh-10-r630-01
- nycmesh-713-r630-01-mgmt
=> Add production servers to DNS

mesh.zone
Remove the `gh-pages-test`, we are not going in that direction with nycmesh.net any longer
=> Remove GH Pages Test

mesh.zone
Add mesh domain `emergency-dev.mesh.nycmesh.net` for David K's project
=> Add David K's project

sld/records.nycmesh.net.tf
Make stats point at the SN3 copy not the SN1 copy. Content was already migrated by DH.
**Approve only, do not merge until designated migration window.**
=> Move stats from SN1 to SN3

mesh.zone, sld/records.nycmesh.net.tf
Do not merge until it is ready for the cut over
=> 23. IPs for SN10 services

sld/records.nycmesh.net.tf
=> Remove map.db.nycmesh.net

mesh.zone
nycmesh-713-rsyslog-temp on Jon
=> Add rsyslog server to mesh.zone

sld/records.nycmesh.net.tf
=> Move forms to sn3

mesh.zone, sld/records.nycmesh.net.tf
When ready, add back the NS record to send traffic back to SN10.
=> Add back SN10

sld/records.nycmesh.net.tf
DO NOT MERGE unless we need to
=> Stateless to sn3 again

infra/ansible/roles/knot-recursive/templates/kresd.conf.j2, infra/terraform/dns.tf, infra/terraform/mesh_dns_servers/ansible.tf, infra/terraform/mesh_dns_servers/vars.tf, infra/terraform/vars.tf
Parameterize the value that points the recursive resolver to a mesh authoritative resolver.
=> Parameterize stub resolver

infra/terraform/prod_sn3.tfvars
Use 10.10.10.10 at SN3
Approvers: You are welcome to approve, but please do not merge.
=> Use 10.10.10.10 for resolver at SN3

infra/terraform/prod_sn10.tfvars, infra/terraform/prod_sn3.tfvars
Use 10.10.10.10 at SN10
Approvers: You are welcome to approve, but please do not merge.
=> Use 10.10.10.10 for resolver at SN10

sld/records.nycmesh.net.tf
Change A record to kubernetes-lb-prod-sn3.nycmesh.net CNAME
=> Migrate gsg-displays to k8s proxy

infra/ansible/roles/dns-telegraf/files/journald.d_conf.yaml, infra/ansible/roles/dns-telegraf/tasks/datadog.yaml
Similar to other repos, simplify how log capturing is setup.
=> Cleanup DD log setup

.github/workflows/deploy.yaml, .github/workflows/deploy_dns_environment.yaml, infra/ansible/roles/knot_authoritative/templates/knot.conf.j2, infra/terraform/dns.tf, infra/terraform/mesh_dns_servers/ansible.tf, infra/terraform/mesh_dns_servers/vars.tf, infra/terraform/vars.tf, mesh.zone, prox.mesh.nycmesh.net
Add tsig keys to use with Let's Encrypt
=> Add TSIG keys

.github/workflows/deploy.yaml
Allow push button deploys (like I want to do now to test the new vpn)
=> Allow workflow_dispatch

mesh.zone
Add 2 domains for nyckml pointing at dev3 and prod1
=> Add nyckml domains

mesh.zone
At Grand St grandmox 10.70.187.202
=> Add FreePBX mesh.zone

mesh.zone, sld/records.nycmesh.net.tf
Change reverse proxy from Daniel Pallas to k8s prod
=> Update Mastodon public IP in mesh.zone

mesh.zone
=> Removing SN1 A names

mesh.zone
=> Update FreePBX IP in mesh.zone

sld/records.nycmesh.net.tf
=> Auth DNS only at 3

sld/records.nycmesh.net.tf
Merge this before https://github.com/nycmeshnet/k8s-infra/pull/98
=> Cutover stateless to SN3

generate_nn.py, infra/ansible/roles/knot_recursive/tasks/doh.yaml
Also a tiny upgrade to a package to force a deploy.
=> Glue records and bug

.github/workflows/deploy.yaml, .github/workflows/sld_terraform.yaml, infra/ansible/roles/knot_authoritative/tasks/main.yaml, sld/README.md
Make the main branch `main` instead of `master`. **Right after merging this, I'll make the corresponding change in the UI.**
=> Update master to main

infra/ansible/roles/knot_recursive/tasks/doh.yaml
=> Fix package version

.github/workflows/deploy_dns_environment.yaml, requirements.txt
Resolves https://github.com/nycmeshnet/nycmesh-dns/security/code-scanning/1
=> Pin ansible

sld/records.nycmesh.net.tf
=> Remove sn1 records

airflow.mesh.nycmesh.net.zone, devairflow.mesh.nycmesh.net.zone, infra/ansible/roles/knot_authoritative/templates/knot.conf.j2, mesh.zone
New zones because tsig + anycast
=> Add airflow

mesh.zone
=> Add A record for meshroom 3d printer mesh.zone

sld/records.nycmesh.net.tf
For https://github.com/nycmeshnet/stripe-redirect/pull/1 to use github pages
=> Pages for stripe
