nycmeshnet/nycmesh-dns

- mesh.zone
I launched an on-mesh Gitlab instance at 10.70.123.5 that I'm willing to maintain. Not sure if grabbing gitlab.mesh is proper DNS etiquette or if you'd prefer something like gitlab.emerson.mesh - up to you.
Thanks for building & launching our .mesh DNS!
> Add gitlab.mesh

- mesh.zone
Leaving unms.mesh in place with a CNAME to not make people's habits and configurations fail all of a sudden
Not strictly necessary, but the UISP/UNMS name change has been a bit confusing to some, I'm hoping this helps move us forward a bit.
> UNMS was renamed to UISP, let's go with the times!

- mesh.zone
Adding a hard link from the internal tv.mesh domain to the Grand Street - 1932 router.
Subject to change once 1932-core is removed!
> Add tv.mesh to zone file

- mesh.zone
Now running off 1934-core which uses a different IP range.
> Changed 1933 TV Server to new static address

- nodensrecords.py
Fixes this error:
```
File "/home/cel/nycmesh-dns/nodensrecords.py", line 14
print "nycmesh-{}-rtr A {}".format(nn, rtrip)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
> Update script for Python v3

- mesh.zone
This was recommended by David Albert to resolve an issue I was having where my `*.andrew.mesh` records were working but `*.andrew.mesh.nycmesh.net` was not resolving.
Basically this issue is, currently public recursive resolvers can't access my authoritative DNS zone, since it's specified by a private IP. 
It would seem the concept of an NS record that points to a private IP doesn't make any sense in the context of public DNS lookups. Our current setup works because if you have private IPs in the public DNS tree, they have to be leaf nodes, otherwise you have problems.
This PR changes my NS record to point to the public address of my remote server. This does mean that these records will fail to resolve if the mesh looses connectivity to the internet, but since this is a VPN server anyway, …
> Change andrew.mesh NS record to point to public IP

- mesh.zone
Adds public wiki IP to improve accessibility.  
- Many potential wiki users who want to learn about Mesh do not have a VPN setup.  
- This change also allows Mesh volunteers to evaluate the wiki as an easier to edit docs replacement with search functionality etc.
> Add public wiki IP to improve accessibility 

- mesh.zone
This updates the IP address of the box in grand, and renames it from meshsvc-grand to grandbox to be easier to type.
> Update DNS record for grandbox

- mesh.zone
Creates a new A record for the current(?) grafana instance. This should make it easier to find and use for volunteers (such as myself 🙃)
> Create A Record for grafana

- mesh.zone
Creates a CNAME for devforms to get traefik working and also make a new "section" in the .zone file for k8s-infra. We're gonna be adding like a million CNAMEs.
> Add CNAME for devforms

- mesh.zone
Adds `forms.mesh.nycmesh.net` for use with the new production meshforms.
> Add forms.mesh.nycmesh.net as CNAME

- mesh.zone
Add CNAMEs for admin and non-admin map services in dev and prod. This is to be used with meshdb.
> Add map CNAMEs

- .github/workflows/pull_request.yaml
- .github/workflows/sld_terraform.yaml
- README.md
- sld/README.md
- sld/provider.tf
- sld/records.nycmesh.net.tf
- sld/records.nycmeshconnect.com.tf
- sld/records.nycmeshconnect.net.tf
- sld/records.themesh.foundation.tf
- sld/records.themesh.nyc.tf
- sld/setup/README.md
- sld/setup/one_time_setup.py
- sld/vars.tf
Manage the following zones via terraform:
1. nycmesh.net
2. nycmeshconnect.com
3. nycmeshconnect.net
4. themesh.foundation
5. themesh.nyc
Before merge:
> Manage second level DNS via terraform

- sld/records.nycmesh.net.tf
Point wiki.nycmesh.net (currently offline) to the future on-prem wiki location (current wiki2.mesh.nycmesh.net)
> Point wiki.nycmesh.net to future on-prem wiki

- sld/records.nycmesh.net.tf
This will allow the following to be:
- db.nycmesh.net
- pgadmin.db.nycmesh.net
- map.db.nycmesh.net
- adminmap.db.nycmesh.net
- los-backend.db.nycmesh.net
- los.nycmesh.net
- forms.nycmesh.net
- devdb.nycmesh.net
- pgadmin.devdb.nycmesh.net
- map.devdb.nycmesh.net
- adminmap.devdb.nycmesh.net
- los-backend.devdb.nycmesh.net
- los.devdb.nycmesh.net
- forms.devdb.nycmesh.net
> Add meshdb domains under nycmesh.net

- sld/records.nycmeshconnect.com.tf
This will allow https://github.com/nycmeshnet/connect-redirect to be used to redirect nycmeshconnect.com -> nycmeshconnect.net
> Point nycmeshconnect.com to github pages

- sld/records.themesh.nyc.tf
Similar to the recent update for `nycmeshconnect.com` this will allow https://github.com/nycmeshnet/themesh.nyc to be used to redirect `themesh.nyc` -> `nycmesh.net`. This takes care of the apex domain and the `www` subdomain at once.
As far as I can tell, this is currently pointed at Digital Ocean, but it doesn't look like anything is running there.
> Point themesh.nyc to github pages

- sld/records.nycmeshconnect.com.tf
- sld/records.nycmeshconnect.net.tf
@OlivierMorf noticed that at least one of the domains is referenced in official documents using the `www` subdomain and recommended that we add those records so that the links work. `nycmeshconnect.net` and `nycmeshconnect.com` are hosted using GitHub pages, so the new subdomains are pointed there.
Thanks Olivier!
> Add www CNAMEs for nycmeshconnect net + com

- sld/records.themesh.foundation.tf
Similar to the recent update for `themesh.nyc` this will allow https://github.com/nycmeshnet/themesh.foundation to be used to redirect `themesh.foundation` -> `nycmesh.net` (now including HTTPS). This takes care of the apex domain and the www subdomain at once.
The domain currently IFRAMEs nycmesh.net and is available via HTTP but not HTTPS.
> Point themesh.foundation to github pages

- sld/records.nycmesh.net.tf
`meet.nycmesh.net` may have been decommissioned.
> Remove the 'meet' subdomain which appears unused

- sld/records.nycmesh.net.tf
I have not been able to find many references to `matrix.nycmesh.net` and it appears to be offline, previously hosted at DigitalOcean.
> Remove the 'matrix' subdomain which appears unused

- mesh.zone
- sld/records.nycmesh.net.tf
This can be merged at any time.
This adds `A` records in the `mesh.nycmesh.net` and `nycmesh.net` zones for an authoritative name server hosted at SN3. This does not cause DNS lookups to flow to that server, there is another PR to do that.
> Add A records for soon to be authoritative server

- mesh.zone
This PR points the `doh.mesh.nycmesh.net` domain to route53. The `doh` subdomain is to be used to host DoH servers, which need valid SSL certificates. The plan is to use route53 to make domain validation using the DNS-01 challenge type easy when there are multiple nameservers for the mesh zone.
> Add NS records for doh.mesh.nycmesh.net

- sld/records.nycmesh.net.tf
Soon, the subdomain will no longer be used by MeshDB, so it can be removed. Yes, it is correct that there is only one record removed.
> Remove the pgadmin subdomain

- sld/records.nycmesh.net.tf
The `status-dev.nycmesh.net` domain appears to be offline.
> Remove the 'status-dev' subdomain which appears unused

- sld/records.nycmesh.net.tf
Grafana hosted on sn3-esxi, through haproxy on sn3-k8s
> Add new Grafana k8s endpoint to records.nycmesh.net.tf

- sld/records.nycmesh.net.tf
I have not been able to find many references to `donate.nycmesh.net` it appears to be offline, previously hosted at DigitalOcean.
As far as I know, donations happen via https://www.nycmesh.net/donate
> Remove the 'donate' subdomain which appears unused

- nycmeshconnect.com.zone
- nycmeshconnect.net.zone
- themesh.nyc.zone
Right now the SOA records (that are not actually in use) are pointing to subdomains like `nycmesh-713-dns-auth-4.themesh.foundation.themesh.foundation`, instead they should just include the hostname
> Only include the hostname in SOA

- mesh.zone
Change `RNAME` in the `mesh.nycmesh.net` SOA record to the more specific `hostmaster` mailbox.
That forwarder is currently forward to me and was setup by Brian.
> Hostmaster email

- mesh.zone
Testing the use of GH Pages for nycmesh.net, this domain will enable custom domain testing
> Add gh-pages-test.mesh to test use of GH Pages

- mesh.zone
This is one of the steps to [migrate](https://github.com/nycmeshnet/nycmesh.net/pull/157) the wiki from `wiki.mesh.nycmesh.net` to `wiki.nycmesh.net`.
A redirect has already been configured in apache on grandbox to redirect `wiki.mesh.nycmesh.net` to `wiki.nycmesh.net` for those with bookmarks. This will be available for as long as the Let's Encrypt cert is valid.
> CNAME wiki.mesh.nycmesh.net to k8s-lb for redirection after cutover

- sld/records.nycmesh.net.tf
Add a layer of indirection (via CNAMEs) for stateless services pointed at the (prod) k8s lb. This is to make it very easy to host these services at multiple locations, and to easily failover via DNS if needed.
> CNAMEs for stateless k8s services

- .github/workflows/pull_request.yaml
- mesh.zone
> The utility checks  zone file syntax and runs semantic checks on the zone content. The executed checks are the same as the checks run by the Knot DNS server.
[kzonecheck](https://manpages.ubuntu.com/manpages/jammy/man1/kzonecheck.1.html)
The idea here is to catch typos in the zone files at PR time, mostly so that I stop needing to bug people for approvals again after I continue making typos.
Example of it finding an issue: https://github.com/nycmeshnet/nycmesh-dns/actions/runs/11849829711/job/33023716149
Example of no issue: https://github.com/nycmeshnet/nycmesh-dns/actions/runs/11849845206/job/33023749749
> Add kzonecheck to pr build

- doh.mesh.nycmesh.net.zone
- mesh.zone
- sld/records.nycmesh.net.tf
Also contains the changes from https://github.com/nycmeshnet/nycmesh-dns/pull/151
This makes it so DNS requests for *.mesh.nycmesh.net go only to the new servers at SN10 and SN3 and not the server(s) at SN1.
Also, fail over stateless services to SN3.
**Do not merge until instructed.**
> Remove the SN1 NS record for the mesh zone

- .github/workflows/deploy.yaml
- infra/ansible/ansible.cfg
- infra/ansible/dns_server.yaml
- infra/ansible/roles/dns-frr/tasks/main.yaml
- infra/ansible/roles/dns-frr/templates/frr.conf.j2
- infra/ansible/roles/dns-frr/templates/iptables.j2
- infra/ansible/roles/dns-frr/templates/netplan_dummy3.yaml.j2
- infra/ansible/roles/knot-recursive/tasks/main.yaml
- infra/ansible/roles/knot-recursive/templates/kresd.conf.j2
- infra/terraform/dev_jon.tfvars
- infra/terraform/dns.tf
- infra/terraform/mesh_dns_servers/ansible.tf
- infra/terraform/mesh_dns_servers/vars.tf
- infra/terraform/prod_sn10.tfvars
- infra/terraform/prod_sn3.tfvars
- infra/terraform/vars.tf
Allow the recursive resolvers to use dedicated IPs for outbound traffic.
> Outgoing IP

- mesh.zone
These legacy domains are currently pointing at grandsvc for redirection, but are no longer used because the domains moved outside of the mesh zone.
The certs for these domains expire on 12/12/24 and will intentionally not be renewed. Merge this some time after that.
> Cleanup meshdb related subdomains from the mesh zone

- sld/records.nycmesh.net.tf
I have not been able to find any references to `monitoring.nycmesh.net` and it appears to be offline. I'm not familiar with hosting at the address it is pointing to now.
> Remove the 'monitoring' subdomain which appears unused

- infra/terraform/dev_jon.tfvars
This will make the beta IP available at jon, in addition to the other 2 locations (until it is removed from the other 2 locations).
> Add the beta ip to jon

- infra/terraform/dev_jon.tfvars
- infra/terraform/prod_sn10.tfvars
- infra/terraform/prod_sn3.tfvars
Point the stub resolvers at the opposite SN's authoritative DNS server IP, which is also on the secondary server at the same SN.
This means that when 10.10.10.10 gets a query for wiki.mesh or wiki.mesh.nycmesh.net, it makes a query to the secondary server (which has less load) at the same SN. If there is no route to the secondary server at the same SN, the query will cross the mesh to the primary server with that IP at the other SN.
> Point stub resolvers away from 10.10.10.11

- mesh.zone
This record points to an IP being used by a server I operate. I do not need the record to point to the server I am operating and therefore it can be removed.
> Remove ebook record

- mesh.zone
These records point to an IP being used by a server I operate. I do not need the records to point to the server I am operating and therefore they can be removed.
> Remove records

- sld/records.nycmesh.net.tf
This is to avoid the <60 second downtime when switching from frr to bird
For: https://github.com/nycmeshnet/k8s-infra/pull/73
**DO NOT MERGE**
> Send stateless services to SN3

- infra/terraform/prod_sn10.tfvars
- infra/terraform/prod_sn3.tfvars
- makereverse.py
This adds new servers to perform "normal" DNS resolution at 10.10.10.11 alongside 10.10.10.10 to maintain compatibility with the current state of things.
You can confirm the current behavior of 10.10.10.11 via: `dig mikrotik.com @10.10.10.11` notice that resolution is successful. This behavior is different than making the same query to an authoritative server (operated by us not mikrotik) where recursion is disabled `dig mikrotik.com @23.158.16.23` which will correctly fail.
Only merge after:
> Use 10.10.10.11 instead of the beta IP

- sld/records.nycmesh.net.tf
Move stateless services and the auth NS record back to SN10 after the outage
> Back to SN10

- mesh.zone
Using this zone to get certs via `DNS-01` means it can only be at one public IP.
> nn in one place

- deploy_knot.sh
- infra/ansible/roles/knot_authoritative/tasks/main.yaml
Not allowing writes by group (`knot`) means the zone can't be flushed, which breaks dynamic updates.
> Allow writes by knot

- airflow.mesh.nycmesh.net.zone
- building-dev.mesh.nycmesh.net.zone
- building.mesh.nycmesh.net.zone
- devairflow.mesh.nycmesh.net.zone
- doh.mesh.nycmesh.net.zone
- generate_nn.py
- ha.mesh.nycmesh.net.zone
- jamesinternalprodtwo.mesh.nycmesh.net.zone
- prox.mesh.nycmesh.net.zone
Set the TTL to `300` (5 minutes) instead of `3600` (1 hour) on the zones that are set up to be used for getting certs via Let's Encrypt's DNS-01 challenge to try to force rechecking more often.
> Set ttl to 300

- sld/records.nycmesh.net.tf
For [slack-redirect](https://github.com/nycmeshnet/slack-redirect/pull/3) to use github pages
> Pages for slack-redirect
